# MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/paypool?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT / RSA key paths
app.jwt.private-key=./key/private_key.pem
app.jwt.public-key=./key/public_key.pem
app.password.private-key=./key/password_private.key
app.password.public-key=./key/password_public.key
